name: Compile Typst Slides and Release

on:
  push:
    branches:
      - main
    paths:
      - 'Curriculum/**/slides/**'
      - '.github/workflows/compile-typst.yml'

permissions:
  contents: write

jobs:
  compile-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Fira Math
        run: |
          gem install fontist
          fontist install "Fira Math"

      - name: Setup Typst 0.12.0
        uses: typst-community/setup-typst@v3
        with:
          typst-version: 0.12.0

      - name: Compile all slides.typ files
        run: |
          mkdir -p compiled-slides
          find Curriculum -type f -path "*/slides/*.typ" | while read file; do
            echo "Compiling $file"
            module_dir=$(dirname "$file")
            module_name=$(echo "$module_dir" | sed 's|Curriculum/||;s|/|_|g')
            typst compile "$file" "compiled-slides/${module_name}.pdf" --root . || echo "❌ Failed: $file"
          done

      - name: Fail if no slides were compiled
        run: |
          if ! ls compiled-slides/*.pdf 2>/dev/null; then
            echo "❌ No slides were compiled!"
            exit 1
          fi

      - name: Create GitHub Release and upload PDFs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-slides
          name: "Latest Compiled Slides"
          body: "Compiled PDFs of all slides in the Curriculum directory."
          files: compiled-slides/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
