name: Compile Typst Slides and Release

on:
  push:
    branches:
      - main
    paths:
      - 'Curriculum/**/slides/**'
      - '.github/workflows/compile-typst.yml'
      - 'typst-athena-slides-template'
      - 'athena-fonts'

permissions:
  contents: write

jobs:
  compile-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          lfs: true
          token: ${{ secrets.ATHENA_FONTS_PAT }}

      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - run: |
          nix build .?submodules=1#

      - name: Create GitHub Release and upload PDFs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-slides
          name: "Latest Compiled Slides"
          body: "Compiled PDFs of all slides in the Curriculum directory."
          files: result/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
